name: MvhAdmin Test Suite
on: [push]

jobs:
  test:
    name: MvhAdmin Tests (Unit / E2E)
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Unit Tests
        run: yarn test:unit
      - name: E2E tests
        run: yarn test:e2e --headless
